

POST {{baseUrl}}/token?grant_type=client_credentials
Authorization: Basic {{autherization}}

###

GET {{baseUrl}}/nubentos.com/ncovapi/2.0.0/cases
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/nubentos.com/ncovapi/2.0.0/todayCases
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/nubentos.com/ncovapi/2.0.0/active
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/nubentos.com/ncovapi/2.0.0/deaths
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/nubentos.com/ncovapi/2.0.0/todayDeaths
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/nubentos.com/ncovapi/2.0.0/recovered
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/nubentos.com/ncovapi/2.0.0/critical
Accept: application/json
Authorization: Bearer {{accessToken}}


###

GET {{baseUrl}}/nubentos.com/ncovapi/2.0.0/casesPerOneMillion
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/nubentos.com/ncovapi/2.0.0/deathsPerOneMillion
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/nubentos.com/ncovapi/2.0.0/totalTests
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/nubentos.com/ncovapi/2.0.0/testsPerOneMillion
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET https://jsonplaceholder.typicode.com/posts

###

GET https://api:branch_detail_view:6379


###

GET https://bilalozcan.site/get.php